labels:
  # Entités PII
  - PERSONNE
  - NOM
  - PRÉNOM
  - NOM_DE_FAMILLE
  - NOM_COMPLET
  - NOM_DE_JEUNE_FILLE
  - ADRESSE
  - ADRESSE_RUE
  - CODE_POSTAL
  - VILLE
  - ÉTAT
  - PAYS
  - NUMÉRO_DE_TÉLÉPHONE
  - NUMÉRO_DE_LIGNE_FIXE
  - NUMÉRO_DE_PORTABLE
  - NUMÉRO_DE_FAX
  - ADRESSE_EMAIL
  - EMAIL_PERSONNEL
  - EMAIL_PROFESSIONNEL
  - DATE_DE_NAISSANCE
  - LIEU_DE_NAISSANCE
  - ÂGE
  - NUMÉRO_DE_SÉCURITÉ_SOCIALE
  - NUMÉRO_DE_CARTE_D'IDENTITÉ
  - NUMÉRO_DE_PASSPORT
  - NUMÉRO_DE_PERMIS_DE_CONDUIRE
  - NUMÉRO_DE_TITRE_DE_SÉJOUR
  - NUMÉRO_D'IDENTIFIANT_ÉLECTEUR
  - NUMÉRO_D'IDENTIFIANT_FISCAL
  - NUMÉRO_D'IDENTIFIANT_PROFESSIONNEL
  - INFORMATIONS_FINANCIÈRES
  - NUMÉRO_DE_CARTE_DE_CRÉDIT
  - NUMÉRO_DE_CARTE_DE_DÉBIT
  - NUMÉRO_DE_COMPTE_BANCAIRE
  - IBAN
  - BIC
  - CODE_SWIFT
  - INFORMATIONS_MÉDICALES
  - DOSSIERS_MÉDICAUX
  - DONNÉES_DE_SANTÉ
  - DONNÉES_GÉNÉTIQUES
  - INFORMATIONS_HANDICAP
  - DONNÉES_BIOMÉTRIQUES
  - EMPREINTE_DIGITALE
  - RECONNAISSANCE_FACIALE
  - SCAN_RÉTINIEN
  - EMPREINTE_VOCALE
  - ADN
  - IDENTIFIANTS_EN_LIGNE
  - NOM_UTILISATEUR
  - PSEUDONYME
  - IDENTIFIANTS_DE_CONNEXION
  - MOT_DE_PASSE
  - QUESTION_DE_SÉCURITÉ
  - ADRESSE_IP
  - ADRESSE_MAC
  - ID_APPAREIL
  - NUMÉRO_DE_SÉRIE
  - UUID
  - ID_PUBLICITAIRE_MOBILE
  - DONNÉES_DE_GÉOLOCALISATION
  - COORDONNÉES_GPS
  - HISTORIQUE_DE_GÉOLOCALISATION
  - LOCALISATION_EN_TEMPS_RÉEL
  - COOKIES
  - IDENTIFIANTS_DE_SUIVI
  - INFORMATIONS_PROFESSIONNELLES
  - INTITULÉ_DU_POSTE
  - EMPLOYEUR
  - HISTORIQUE_DE_CARRIÈRE
  - SALAIRE
  - NUMÉRO_D'EMPLOYÉ
  - RÉFÉRENCES_PROFESSIONNELLES
  - INFORMATIONS_ÉDUCATIVES
  - DIPLÔME
  - ÉCOLE
  - NOTES
  - CERTIFICATS
  - ÉTAT_CIVIL
  - GENRE
  - NATIONALITÉ
  - CITOYENNETÉ
  - PHOTOGRAPHIE
  - PHOTO_DE_FAMILLE
  - VIDÉO_PERSONNELLE
  - ENREGISTREMENT_AUDIO
  - BOÎTE_VOCALE
  - SIGNATURE
  - PRÉFÉRENCES_PERSONNELLES
  - INTÉRÊTS
  - LOISIRS
  - HABITUDES_D'ACHAT
  - PRÉFÉRENCES_ALIMENTAIRES
  - HISTORIQUE_DE_NAVIGATION
  - VISITES_DE_SITES_WEB
  - HISTORIQUE_DE_RECHERCHE
  - HISTORIQUE_DE_TÉLÉCHARGEMENT
  - COMMUNICATION_PRIVÉE
  - MESSAGES
  - EMAILS
  - LETTRES
  - CONVERSATIONS_SUR_LES_RÉSEAUX_SOCIAUX
  - INFORMATIONS_FAMILIALES
  - NOMS_DES_MEMBRES_DE_LA_FAMILLE
  - INFORMATIONS_SUR_LES_ENFANTS
  - INFORMATIONS_SUR_LE_CONJOINT
  - HISTORIQUE_FAMILIAL
  - INFORMATIONS_SUR_LE_VÉHICULE
  - NUMÉRO_D'IMMATRICULATION
  - NUMÉRO_DE_PLAQUE_D'IMMATRICULATION
  - MODÈLE_DE_VÉHICULE
  - VIN
  - DONNÉES_DES_RÉSEAUX_SOCIAUX
  - PROFILS_DES_RÉSEAUX_SOCIAUX
  - PUBLICATIONS
  - AMIS_ET_ABONNÉS
  - RELATIONS
  - INFORMATIONS_PARTAGÉES
  - INFORMATIONS_FISCALES
  - NUMÉRO_FISCAL
  - DÉCLARATIONS_FISCALES
  - INFORMATIONS_SUR_LE_REVENU
  - INFORMATIONS_LÉGALES
  - CASIER_JUDICIAIRE
  - INFORMATIONS_SUR_LES_PROCÈS
  - STATUT_LÉGAL
  - INFORMATIONS_D'ASSURANCE
  - NUMÉRO_DE_POLICE_D'ASSURANCE
  - DÉTAILS_DE_LA_COUPERTURE
  - RÉCLAMATIONS_D'ASSURANCE
  - IDENTIFIANTS_GOUVERNEMENTAUX
  - NUMÉRO_DE_CONTRIBUABLE
  - NUMÉRO_DE_BÉNÉFICIAIRE
  - NUMÉRO_D'IDENTIFICATION_GOUVERNEMENTAL
  - OPINIONS_POLITIQUES
  - CROYANCES_RELIGIEUSES
  - CROYANCES_PHILOSOPHIQUES
  - ADHÉSION_SYNDICALE
  - ORIENTATION_SEXUELLE
  - STATUT_MILITAIRE
  - INFORMATIONS_DE_VOYAGE
  - ITINÉRAIRES
  - RÉSERVATIONS
  - HISTORIQUE_DE_VOYAGE
  - INFORMATIONS_SUR_LE_VISA
  - DONNÉES_DE_TRANSACTION
  - HISTORIQUE_D'ACHAT
  - FACTURES
  - REÇUS
  - COMMANDES_EN_LIGNE
  - INFORMATIONS_D'ABONNEMENT
  - ABONNEMENTS_AUX_SERVICES
  - NUMÉROS_D'ABONNÉ
  - PRÉFÉRENCES_D'ABONNEMENT
  - DONNÉES_DES_CAPTEURS
  - DONNÉES_DE_MONTRE_INTELLIGENTE
  - DONNÉES_DE_SUIVI_FITNESS
  - DONNÉES_D'APPAREIL_DE_SANTÉ
  - INFORMATIONS_DE_SÉCURITÉ
  - QUESTIONS_DE_SÉCURITÉ
  - RÉPONSES_DE_SÉCURITÉ
  - MÉTADONNÉES
  - HORODATAGE
  - INFORMATIONS_SUR_LE_FICHIER
  - MÉTADONNÉES_D'IMAGE
  - INFORMATIONS_SUR_LA_LANGUE
  - LANGUES_PARLÉES
  - PRÉFÉRENCES_LINGUISTIQUES
  - INFORMATIONS_CULTURELLES
  - ORIGINE_ETHNIQUE
  - TRADITIONS_CULTURELLES
  - HABITUDES
  - HABITUDES_DE_CONSOMMATION
  - HABITUDES_DE_COMMUNICATION
  - JOURNAUX_D'ACCÈS
  - ENREGISTREMENTS_DE_CONNEXION
  - HISTORIQUE_D'ACCÈS
  - ADRESSE_IP_DE_CONNEXION
  - INFORMATIONS_DE_LICENCE
  - LICENCES_PROFESSIONNELLES
  - CERTIFICATIONS
  - NUMÉROS_DE_LICENCE
  - DONNÉES_D'INTERACTION_CLIENT
  - ENREGISTREMENTS_D'APPEL
  - CHATS_D'ASSISTANCE
  - COMMENTAIRES_ET_AVIS
  - INFORMATIONS_SUR_LE_CONTRAT
  - DÉTAILS_DE_L'ACCORD
  - SIGNATURES
  - TERMES_SPÉCIFIQUES
  - PRÉFÉRENCES_MARKETING
  - CONSENTEMENTS
  - PRÉFÉRENCES_DE_COMMUNICATION
  - HISTORIQUE_DES_CAMPAGNES
  - DONNÉES_TIERS
  - INFORMATIONS_AGRÉGÉES
  - INFORMATIONS_DES_BROKERS_DE_DONNÉES
  - PROFILS_ENRICHIS
  - INFORMATIONS_SUR_LE_DROIT_D'AUTEUR
  - ŒUVRES_SOUS_DROITS_D'AUTEUR
  - NUMÉROS_D'ENREGISTREMENT
  - INFORMATIONS_DE_PARRAINAGE
  - INFORMATIONS_DE_RÉFÉRENCE
  - RELATION_DE_PARRAINAGE
  - INFORMATIONS_SUR_L'IMMOBILIER
  - PROPRIÉTÉS_POSSEDÉES
  - ADRESSES_DES_PROPRIÉTÉS
  - VALEURS_DES_PROPRIÉTÉS
  - DONNÉES_D'APPLICATION_MOBILE
  - AUTORISATIONS_D'APPLICATION
  - DONNÉES_COLLECTÉES_PAR_L'APPLICATION
  - ÉVÉNEMENTS_DE_LA_VIE
  - MARIAGE
  - NAISSANCE_D'ENFANT
  - DÉCÈS_DANS_LA_FAMILLE
  - CHANGEMENTS_DE_CARRIÈRE

  # Entités de Gouvernance d'Entreprise & Exécutives
  - "Entreprise"
  - "Dirigeants d'entreprise"
  - "Conseil d'Administration"
  - "Comité d'Audit"
  - "Directeur Financier (CFO)"
  - "Directeur Général (CEO)"
  - "Directeur des Opérations (COO)"
  - "Directeur du Développement Durable (CSO)"
  - "Directeur Technique (CTO)"
  - "Directeur Marketing (CMO)"
  - "Conseil Juridique"
  - "Secrétaire Général"
  - "Comité de Gouvernance et Conformité"
  - "Gestionnaire des Risques"
  - "Administrateurs Indépendants"
  - "Actionnaires"
  - "Parties Prenantes"
  - "Avocats d'Entreprise"
  - "Responsables des Relations Investisseurs"
  - "Comité Consultatif"
  - "Experts en Gouvernance"

  # Entités Financières
  - "Investisseurs Institutionnels"
  - "Sociétés de Capital-Investissement"
  - "Fonds Speculatifs"
  - "Caisses de Retraite"
  - "Fonds Souverains"
  - "Sociétés de Capital Risque"
  - "Banques d'Investissement"
  - "Banques de Détail"
  - "Agences de Notation de Crédit"
  - "Compagnies d'Assurance"
  - "Cabinets d'Audit"
  - "Conseillers Fiscaux"
  - "Fonds ESG"
  - "Régulateurs Financiers"
  - "Bourses"
  - "Autorités Monétaires"
  - "Commissions des Valeurs Mobilières"
  - "Sociétés de Gestion d'Actifs"
  - "Sociétés de Gestion de Fortune"
  - "Créanciers d'Entreprise"
  - "Détenteurs de Dette"

  # Entités ESG & Durabilité
  - "Agences de Notation ESG"
  - "Fournisseurs de Données ESG"
  - "Comité de Développement Durable"
  - "Groupes de Défense de l'Environnement"
  - "Organisations des Droits de l'Homme"
  - "Négociants de Crédits Carbone"
  - "Organisations Non Gouvernementales (ONG)"
  - "Comités de Responsabilité Sociale"
  - "Syndicats"
  - "Groupes de Défense des Consommateurs"
  - "Équipes de Responsabilité Sociale des Entreprises (RSE)"
  - "Agences Environnementales"
  - "Comités d'Éthique"
  - "Responsables de la Diversité"
  - "Investisseurs à Impact Social"
  - "Analystes en Durabilité"
  - "Fonds d'Impact"

  # Entités Politiques & Gouvernementales
  - "Gouvernements"
  - "Agences Gouvernementales"
  - "Autorités de Régulation"
  - "Partis Politiques"
  - "Législateurs"
  - "Groupes de Lobbying"
  - "Think Tanks de Politiques Publiques"
  - "Organismes d'Application de la Loi"
  - "Ministères des Finances"
  - "Ministères des Affaires Étrangères"
  - "Chambres de Commerce"
  - "Missions Diplomatiques"
  - "Fonds Monétaire International (FMI)"
  - "Banque Mondiale"
  - "Organisation Mondiale du Commerce (OMC)"
  - "Organisations Géopolitiques"
  - "Unités de Sanctions (ex : OFAC)"
  - "Ministères du Commerce"
  - "Organisations Intergouvernementales"
  - "Entrepreneurs Militaires"

  # Entités Légales
  - "Cours Internationales"
  - "Départements Juridiques d'Entreprise"
  - "Cabinets d'Avocats"
  - "Comités de Conformité"
  - "Veilleurs Anticorruption"
  - "Organismes de Résolution des Conflits"
  - "Bureaux de Propriété Intellectuelle"
  - "Autorités de Protection des Données"
  - "Cabinets d'Avocats en Cybersécurité"
  - "Avocats de Droits de l'Homme"
  - "Autorités de Concurrence du Marché"
  - "Autorités Antitrust"
  - "Organes de Sanctions"

  # Médias & Entités de Société Civile
  - "Agences de Presse"
  - "Journalistes d'Investigation"
  - "Organisations de Lanceurs d'Alerte"
  - "Transparency International"
  - "Groupes des Droits Civiques"
  - "Organisations de Surveillance de la Liberté d'Information"
  - "ONG Axées sur la Corruption"
  - "Entreprises de Relations Publiques"
  - "Organisations de Libertés Civiles"
  - "Journalistes"
  - "Plateformes de Médias Sociaux"
  - "Blogueurs d'Investigation"
  - "Organisations de Vérification des Faits"

  # Entités Géopolitiques & de Renseignement
  - "Agences Nationales de Renseignement"
  - "Organisations Militaires"
  - "Entrepreneurs de Défense"
  - "Analystes Géopolitiques"
  - "Cabinets de Conseil en Risques Globaux"
  - "Équipes de Renseignement Stratégiques"
  - "Unités de Contre-Terrorisme"
  - "Unités d'Application des Sanctions"
  - "Agences de Sécurité Nationale"
  - "Cabinets de Conseil en Risques Politiques"
  - "Attachés Diplomatiques"

  # Éléments de Temps
  - "Date"
  - "Heure"
  - "Mois"
  - "Année"
  - "Semaine"
  - "Jour"
  - "Heure"
  - "Année Fiscale"
  - "Trimestre"
  - "Rapport Annuel"
  - "Période d'Audit"
  - "Cycle Budgétaire"
  - "Période de Sanctions"
  - "Cycle Électoral"
  - "Chronologie des Fusions & Acquisitions"

  # Entités Géographiques & de Localisation
  - "Siège Social"
  - "Bureaux Régionaux"
  - "Juridiction de l'Entreprise"
  - "Pays Sanctionnés"
  - "Zones de Commerce"
  - "Emplacements de la Chaîne d'Approvisionnement"
  - "Ambassades"
  - "Frontières Internationales"
  - "Zones de Libre-Échange"
  - "Zones Sinistrées"
  - "Zones de Conflit"

allowed_nodes:
  # Nœuds de Gouvernance
  - "Conseil d'Administration"
  - "Comité d'Audit"
  - "Directeur Financier (CFO)"
  - "Directeur Général (CEO)"
  - "Directeur des Opérations (COO)"
  - "Directeur du Développement Durable (CSO)"
  - "Directeur Technique (CTO)"
  - "Comité de Gouvernance et Conformité"
  - "Administrateurs Indépendants"
  - "Dirigeants d'Entreprise"
  - "Actionnaires"
  - "Parties Prenantes"
  - "Avocats d'Entreprise"
  - "Comité Consultatif"
  - "Experts en Gouvernance"

  # Nœuds Financiers
  - "Investisseurs Institutionnels"
  - "Fonds Speculatifs"
  - "Sociétés de Capital-Investissement"
  - "Sociétés de Capital Risque"
  - "Banques"
  - "Banques d'Investissement"
  - "Agences de Notation de Crédit"
  - "Fonds Souverains"
  - "Autorités Monétaires"
  - "Caisses de Retraite"
  - "Cabinets d'Audit"
  - "Fonds ESG"
  - "Analystes Financiers"
  - "Créanciers d'Entreprise"
  - "Détenteurs de Dette"
  - "Conseillers en Gestion de Fortune"

  # Nœuds ESG & Durabilité
  - "Agences de Notation ESG"
  - "Fournisseurs de Données ESG"
  - "Agences Environnementales"
  - "Organisations des Droits de l'Homme"
  - "Sociétés de Négociation de Carbone"
  - "Comités de Responsabilité Sociale"
  - "Groupes de Défense de l'Environnement"
  - "ONG"
  - "Équipes de Responsabilité Sociale d'Entreprise (RSE)"
  - "Groupes de Défense des Consommateurs"
  - "Analystes en Durabilité"
  - "Fonds d'Impact"

  # Nœuds Politiques
  - "Gouvernements"
  - "Partis Politiques"
  - "Autorités de Régulation"
  - "Organisations Géopolitiques"
  - "Missions Diplomatiques"
  - "Think Tanks de Politiques Publiques"
  - "Chambres de Commerce"
  - "Agences d'Application de la Loi"
  - "Douanes et Protection des Frontières"
  - "Organisations Internationales du Commerce"
  - "Fonds Monétaire International (FMI)"
  - "Ambassades Étrangères"

  # Nœuds Légaux
  - "Cours Internationales"
  - "Départements Juridiques d'Entreprise"
  - "Cabinets d'Avocats"
  - "Organismes de Résolution des Conflits"
  - "Autorités Antitrust"
  - "Autorités de Concurrence du Marché"
  - "Responsables de la Conformité"
  - "Autorités de Protection des Données"
  - "Veilleurs Anticorruption"

  # Nœuds Géopolitiques
  - "Agences Nationales de Renseignement"
  - "Organisations Militaires"
  - "Entrepreneurs de Défense"
  - "Agences de Sécurité Nationale"
  - "Analystes des Risques Politiques"
  - "Équipes de Renseignement Stratégiques"
  - "Organes d'Application des Sanctions"
  - "Attachés Diplomatiques"

  # Nœuds Médias & Société Civile
  - "Agences de Presse"
  - "Journalistes"
  - "Journalistes d'Investigation"
  - "Organisations de Lanceurs d'Alerte"
  - "Transparency International"
  - "Groupes des Droits Civiques"
  - "Cabinets de Relations Publiques"
  - "Organisations de Surveillance des Droits de l'Homme"
  - "Analystes des Médias Sociaux"

  # Nœuds de Temps
  - "Année Fiscale"
  - "Période d'Audit"
  - "Rapport Annuel"
  - "Cycle Budgétaire"
  - "Cycle Électoral"
  - "Chronologie des Fusions & Acquisitions"

  # Nœuds Géographiques
  - "Siège Social"
  - "Bureaux Régionaux"
  - "Pays Sanctionnés"
  - "Zones de Commerce"
  - "Ambassades"
  - "Nœuds de la Chaîne d'Approvisionnement"
  - "Zones de Libre-Échange"
  - "Zones de Conflit"

allowed_relationships:

  - "collabore_avec"
  - "rend_compte_à"
  - "influence"
  - "possède_des_actions_dans"
  - "finance"
  - "sanctionne"
  - "certifie"
  - "régule"
  - "audite"
  - "fournit_à"
  - "surveille"
  - "enquête_sur"
  - "poursuit"
  - "impose_des_sanctions_à"
  - "applique"
  - "litige_avec"
  - "fait_du_lobbying"
  - "prête_à"
  - "fournit_des_services_à"
  - "commerce_avec"
  - "consultant_pour"
  - "partenaire_avec"
  - "conseille"
  - "est_en_compétition_avec"
  - "stratégise_avec"
  - "gère"
  - "supervise"
  - "détient_une_part_majoritaire_dans"
  - "est_une_filiale_de"
  - "est_la_société_mère_de"
  - "a_une_alliance_stratégique_avec"
  - "est_affilié_à"
  - "a_une_coentreprise_avec"
  - "licencie_la_technologie_à"
  - "fournit_un_financement_à"
  - "est_réglementé_par"
  - "est_audité_par"
  - "est_membre_de"
  - "a_un_contrat_avec"
  - "a_un_différend_avec"
  - "est_acquis_par"
  - "a_fusionné_avec"
  - "s'est_désengagé_de"
  - "est_poursuivi_par"
  - "emploie"
  - "est_gouverné_par"
  - "viole_la_réglementation_de"
