name: CI/CD for Weavestruct API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Récupère le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure l'environnement Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Installe les dépendances principales
    - name: Install main dependencies
      run: pip install -r requirements.txt

    # Installe les dépendances de test
    - name: Install test dependencies
      run: pip install -r requirements_test.txt

    # Lance les tests avec pytest
    # - name: Run tests
    #   run: pytest

    # Construire l'image Docker
    - name: Build Docker image
      run: docker build -t weavestruct-api:${{ github.sha }} .

    # Se connecter au registre Docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Pousser l'image Docker vers le registre
    - name: Push Docker image
      run: docker push weavestruct-api:${{ github.sha }}

  notify-infra:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI in Services Repository
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.actions.createWorkflowDispatch({
              owner: 'Artemis-IA',
              repo: 'mlops_backend',
              workflow_id: 'deploy.yml',
              ref: 'main',
            });



            