name: Update Swagger Documentation

on:
  push:
    branches:
      - main

jobs:
  update-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI Server
        run: |
          nohup uvicorn src.main:app --host 127.0.0.1 --port 8008 > server.log 2>&1 &
          sleep 10  # Donne le temps au serveur de démarrer
          echo "Server logs:"
          cat server.log

      - name: Test API Accessibility
        run: |
          curl -I http://127.0.0.1:8008/openapi.json


      - name: Fetch OpenAPI Specification
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          echo "Fetching OpenAPI Specification from $API_URL"
          curl -o docs/static/swagger.json http://127.0.0.1:8008/openapi.json
          if [ $? -ne 0 ]; then
            echo "Failed to fetch OpenAPI specification"
            exit 1
          fi
          echo "OpenAPI specification saved to docs/static/swagger.json"

      - name: Deploy Documentation
        run: |
          pip install mkdocs-material
          mkdocs gh-deploy