name: Update OpenAPI Specification and Documentation

on:
  push:
    branches:
      - main

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
      # Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer les dépendances système
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libopenblas-dev liblapack-dev

      # 2. Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-material

      # Générer le fichier openapi.json
      - name: Generate OpenAPI Specification
        run: |
          python src/scripts/generate_openapi.py

      # Générer la documentation MkDocs
      - name: Deploy Documentation
        run: |
          mkdocs build


    